### ISSUE TITLE
Add time option

### ISSUE THREAD

**Issue by PaulMonnery** [Yohannfra/JenRik#1]
It would be nice to be able to see if the program runs under a certain amount of time.
Like add an optional check for time and give the maximal value to pass the test.
Maybe also being able to put timeout, just in case!
Thanks

**Comment by Yohannfra** [comment]
That's a good idea and should be quite simple to do, i'll work on it asap

**Comment by Yohannfra** [comment]
@PaulMonnery  feature implemented and on master, thanks

**Comment by Yohannfra** [comment]
fixed in 8689d3d9523a5bed4814faaf82cacf406fa28378
