### ISSUE TITLE
Add input command

### ISSUE THREAD

**Issue by LorenzoRosmarino** [Yohannfra/JenRik#5]
An `input` command could be useful.

You could use the "manual" pipe [as currently done](https://github.com/Yohannfra/JenRik/blob/master/JenRik#L165), or pass the string to [Popen.communicate](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate), which pipes the string in the standard input of the process

It can already pipe the stdout and stderr to other programs before checking the results, piping to stdin would seem logical.

**Comment by Yohannfra** [comment]
That's a good idea thanks :) , waiting can you work on a pull request ?

**Comment by Yohannfra** [comment]
the commit d18dd75b3bda85988a6da50d2d416e74030e824d add a **stdin** command that will write in the stdin of the process. See the README for an example.

Thanks you for you contribution
